### ISSUE TITLE
seberapa penting belajar clean architecture 

### ISSUE THREAD

**Issue by AzzamSyakir** [slowy07/your_question#1]
halo bang arfy, mau nanya sepenting apa clean arch untuk sebuah projek, dan apa companyakan beri saya nilai plus jika bisa clean arch

**Comment by slowy07** [comment]
@AzzamSyakir https://youtu.be/CWJ2CfwszQE 💯

**Comment by AzzamSyakir** [comment]
mantap thanks bg
