### ISSUE TITLE
Seputar DevOps

### ISSUE THREAD

**Issue by ZahidWazifa** [slowy07/your_question#10]
Menurut kakak apakah pekerjaan devops masih relate dengan  dunia tech untuk saat ini, karena banyaknya tools yang memungkinan pekerjaan itu tergantikan dan jika iya apakah kakak ada saran untuk bidang lain yang masi berkaitan dengan jaringan  kak? Soalnya saya tertarik di bidang tersebut. Terima kasih

**Comment by slowy07** [comment]
https://youtu.be/8KaCNrbXgBM?si=U1B5U-1RMc0gqgTf
