### ISSUE TITLE
Bingun dalam membuat sesuatu setelah belajar pemograman

### ISSUE THREAD

**Issue by yazidistiqlall** [slowy07/your_question#11]
Halo mas. izin bertanya mas saya kan sempat mengikuti kelas pemograman dasar, saya sudah belajar beberapa bahasa pemograman, setiap sehabis balajar semisal belajar python dasar, sudah saya ikuti alur nya dan paham, setelah mempelajari nya hingga seleasi saya malah bingung kedepannya gimana, semisal nya bingung ingin buat project apa dan ujung ujung nya ga saya lanjutin dan banyak materi yang saya lupa untuk mengatasi nya bagaimana ya mas? terimakasih sebelumnya

**Comment by ryugenxd** [comment]
ini kayak nya kesalasan dari target awal , biasanya kalau kaya gini awalnya itu niat nya cuma belajar bahasa pemrograman bukan untuk membuat sesuatu dengan bahasa pemrograman :)

**Comment by slowy07** [comment]
https://youtu.be/ROhMxga0CxE?si=a71Bun4of1KtQj5Y 🚀
