### ISSUE TITLE
Ijin nanya seputar BackEnd Bang

### ISSUE THREAD

**Issue by Ramdoni007** [slowy07/your_question#15]
salam kenal bang ijin nanya seputar dunia BackEnd di Jaman sekrang gimana ya bang untuk pick bahasa sendiri fokus di satu aja contoh nya Java,Go,JS, python pilih salah satu yang kita suka perdalam atau pilih sesuai kebutuhan market sekarang bang ... hehehe dan kalo menurut abang lebih setuju ke arah mana specialist di sesuatu teknologi atau Plural Random menguasai beberapa teknologi tapi tidak sampe dalem banget kaya specialist ( biasanya orang2 ini yang ngejar trend market kearah mana yang lagi naik di ikuti ) :) 

maaf sedikit OOT saya juga user Vim baru banks hehehe :) ijin SS setUp terminal = 
![editorKecew](https://github.com/slowy07/your_question/assets/62313268/e680f8b3-27d5-46a3-9a42-6c9f0751764b) 
![kecew juga](https://github.com/slowy07/your_question/assets/62313268/c7ab14ee-f39b-4cb1-bc76-9ed6f79baebb)

**Comment by slowy07** [comment]
https://youtube.com/live/zFf-ymjlk5I?feature=share
