### ISSUE TITLE
Tips Menulis Catatan/Dokumentasi

### ISSUE THREAD

**Issue by adithyaric** [slowy07/your_question#16]
> Saya sering baca literasi dari buku, blog dan terutama video youtube (tutorial dkk).

Tapi dari ilmu-ilmu yang sudah saya dapat kadang lost track, lupa dan bingung untuk ambil inti dari topik yang sudah dipelajari tersebut. 

Mungkin Kak Arfy bisa berbagi cara mencatat yang baik (membuat dokumentasi yang jelas dan runtut). Terimakasih 👍

> https://youtu.be/pjmejUE5io4?si=z-kZuBdSZbMWyT4s

**Comment by slowy07** [comment]
https://youtube.com/live/zFf-ymjlk5I?feature=share
