### ISSUE TITLE
fomo dan merasa kewalahan karena resource udah terlalu banyak.

### ISSUE THREAD

**Issue by kucengorenji** [slowy07/your_question#18]
mas, pernah ngerasa kaya pengen belajar sesuatu ngga tiba2 saat dapat inspirasi project/showcase orang lain. entah apa pun itu jenisnya, bisa jadi uiux, coding backend, front end, ai/ml, dll.

saya cukup sering merasa kewalahan untuk mulai dari mana karena resource belajar yang saya simpan sudah terlalu banyak dan rasa fomo yang makin lama semakin besar karena perasaan ga mau kalah. sampai2 pas mau belajarnya udah ga minat lagi karena udah pusing sama proses milihnya duluan.

kalau udah kaya gitu, menurut mas gimana bisa balik ke fokus awal sama goal kita sendiri? misalnya cuma fokus di backend atau front end aja, tapi tetap bisa catchup sama trend terbaru (sering kita sebut sebagai T shaped skill)

**Comment by slowy07** [comment]
https://youtu.be/IhKyRo46EuY?si=Y8g_-XAfktwXQK1Z
