### ISSUE TITLE
tutorial vim/neovim

### ISSUE THREAD

**Issue by haniframadhani** [slowy07/your_question#19]
request bikin tutorial pakai vim/neovim, karena udah biasa pake vscode dan belum pernah pake code editor berbasis terminal jadi bingung pake neovim.

**Comment by luisadha** [comment]
pakai nvchad config biar gak perlu setup2 @haniframadhani

**Comment by haniframadhani** [comment]
maksudnya bukan setup atau config vim/neovim tapi tutorial penggunaan dari vim/neovim. soalnya saya kesulitan dalam menggunakan vim/neovim seperti navigasi, shortcut, dan lain-lain

**Comment by luisadha** [comment]
> maksudnya bukan setup atau config vim/neovim tapi tutorial penggunaan dari vim/neovim. soalnya saya kesulitan dalam menggunakan vim/neovim seperti navigasi, shortcut, dan lain-lain

Hahah kalau soal itu saya juga awam sih gak jago2 amat

**Comment by slowy07** [comment]
https://youtube.com/live/zFf-ymjlk5I?feature=share
