### ISSUE TITLE
Ijin bertanya mengenai tutorial python #16 Dictionary

### ISSUE THREAD

**Issue by boltthunderbolt** [slowy07/your_question#20]
Tipe data dictionary nilainya apa bisa lebih dari 1?
Misal, pekerjaan, terus nilainya lebih dari satu dan jika kita memanggil salah satu jenis pekerjaan dari index "pekerjaan" itu gimana caranya?

**Comment by slowy07** [comment]
halo @boltthunderbolt !, kamu bisa mencoba dengan cara dibawah ini jika ingin menambahkan nilai dari key `pekerjaan` lebih dari satu, bisa menggunakan `list` atau `dict` itu sendiri

```py
data_saya = {
	"nama": "arfy",
	"pekerjaan": {
		"main": "programmer",
		"role": ["software testing", "Front end"]
}

# contoh menghasilkan value `software testing`
print(data_saya["pekerjaan"]["role"][0]")
# contoh menghasilkan value `programmer`
print(data_saya["pekerjaan"]["main"])
```

terima kasih 🚀

**Comment by boltthunderbolt** [comment]
Udh ku coba terapkan ini ke praktek, tapi memanggil nilai rolenya dengan variabel dengan tipe data integer. Pada saat dijalankan, error ditampilkan
"tuple must integer or slices not 'str'" padahalkan manggil index harus integer. Kira kira dimana letak kesalahannya?

**Comment by slowy07** [comment]
halo @boltthunderbolt !, sepertinya ada masalah dimana untuk fungsi ``print()`` ada terdapat tanda `"` dan kekurangan tutup kurung kurawal (`}`) , setelah dijalankan kode diatas maka akan berjalan seperti dibawah ini 
![image](https://github.com/slowy07/your_question/assets/40540262/9407f97c-f55e-4d69-8e5e-80be885e3c73)

**Comment by slowy07** [comment]
issue close ✅
