### ISSUE TITLE
Pertanyaan terkait AI atau machine learning dan data struktur dan algoritma

### ISSUE THREAD

**Issue by Naufalfdh19** [slowy07/your_question#22]
permisi ka mau tanya, cara kaka belajar konsep AI, data struktur dan algoritma itu bagaimana ya ka? latihan aja kah untuk menguasai? soalnya saya selalu stack di rekrusif yang cukup sulit dibayangkan. Saya mau juga gitu bisa mecahin masalah leetcode, saya punya idenya tapi implementasi code-nya cukup sulit

**Comment by slowy07** [comment]
https://youtube.com/live/zFf-ymjlk5I?feature=share
