### ISSUE TITLE
Mengapa LSP saya khususnya untuk bahasa lua tidak aktif saat baru saja menginstall nvchad di windows

### ISSUE THREAD

**Issue by Araryarch** [slowy07/your_question#26]
![image](https://github.com/user-attachments/assets/276caa01-a61e-4dce-9711-f0357ce7b11a)

tulisan text tidak ada warna dan saya juga sudah menginstall daripada lua lang server, namun berjalan baik ke file html dan css

**Comment by slowy07** [comment]
https://youtube.com/live/kVqkgerh9HU?feature=share bisa dilihat disini ya untuk jawabannya
