### ISSUE TITLE
butuh pandangan aja darimu

### ISSUE THREAD

**Issue by rgarestuk** [slowy07/your_question#32]
bang mo sedikt crt mohon jawab dengan agak berbobot, gua kan msh mahasiswa jurusan sistem informasi kebetulan udh semester 7 dan di univ gua itu dikasih 2 jalur pilihan bisnis (gua gk tau yg bisnis ini sebutannya jalurnya apa) sama developer dan gua putusin buat ambil jalur developer karena gua udh beli course/bootcamp fullstack web developer karena ya sayang aja gitu gua udh berani investasi buat masa depan kebetulan course/bootcamp yang gua beli juga lifetime jadi bisa buat calon anak gua nanti dan gua juga sebenernya suka sama coding walaupun ya agak berat buat mempelajarinya, dan gua sendiri kalo ada video software engineer lewat diberanda yt kyk day in my life software engineer gue liat ada yg dari meta, google, dsb.  disitu jujur aja gua merasa termotivasi isi hati gua tu "wah jirr hebat banget bisa jadi software engineernya di meta sama google tempat kerjanya juga enak" cuman permasalahannya gua tu kyk ngerasa "kok gua tu merasa disini sini aja ya progress gua" gua tu terlalu lama mempelajari js karena gua tu blm ngerti sepenuhnya js itu sendiri ya sebenernya gua merasa ada perkembangan sih yg dulu gua susah ngerti apa itu function dan akhirnya skrng gua tau apa itu function secara jelas. jadi inti dari permasalahan dari gua tu merasa progress bljr dari course/bootcamp gua itu tertunda karena gua juga harus mempelajari bahasa yang dikuliah yg udh sampe laravel. dan gue juga meskipun termotivasi gue tu msh sering mls buat bljr karena ya sekalinya stuck dan dah mikirin cara fix lama banget ya gue jadinya mls dan nunda. gue pen minta saran pendapat dong biar gue gk gampang mls kalo udh stuck dalam hal belajar karena gue udh termotivasi nih trs gue bljr trs stuck trs mls abis tu termotivasi lagi bljr lagi, mls lagi gitu aja trs siklusnya, dan pendapatnya juga soal gua bljr dicourse/bootcamp terhambat karena gua hrs ikutin alur diuniv yg udh jauh. 
"btw gua udh mau nyusun skripsi masih mikirin judulnya apa dan apa yang mau gua bikin" 
thanks bang udh luangin buat baca walaupun panjang

**Comment by slowy07** [comment]
https://www.youtube.com/watch?v=Z1FXA0nnTAo&t=188s
