### ISSUE TITLE
Model import file main - Python

### ISSUE THREAD

**Issue by rulanugrh** [slowy07/your_question#5]
Permsi bang arfy, izin bertanya kalau model import file main untuk file lain terus file lainnya juga import file utama boleh tidak bang ? Contohnya kaya gini bang, saya punya file `logic.py` dan  file `main.py`

![image](https://github.com/slowy07/your_question/assets/88574877/0555f2f6-480e-48ed-8cd7-ffec39971132)

![image](https://github.com/slowy07/your_question/assets/88574877/268c8229-ee38-4cad-95af-ed4df423c890)

**Comment by slowy07** [comment]
https://youtu.be/NNYzftR-jLc
