### ISSUE TITLE
meningkatkan logic untuk menyelesaikan sebuah problem

### ISSUE THREAD

**Issue by Fahmi-S** [slowy07/your_question#6]
mau meningkatkan logic untuk solve problem cmn bingung gmn, dan apakah penggunaan AI untuk mengerjakan project itu tidak bagus?, seperti, saya sering sekali menggunakan chatgpt untuk membuat sintaks sesuai dengan logic yang saya berikan. apakah bad practice?

**Comment by slowy07** [comment]
@Fahmi-S  https://www.youtube.com/watch?v=xZFm6C1oKeg
