### ISSUE TITLE
Ask: Specialist atau Generalist

### ISSUE THREAD

**Issue by rulanugrh** [slowy07/your_question#7]
Halo bang arfy, sekarang teknologi sudah makin canggih, banyak sekali update-an yang bener bener mendesak kita untuk selalu upgrade skill. Namun karena itulah membuat kita bingung, manakah yang lebih baik tetap mempelajari yang specialist yang merupakan passion kita atau secara general.

![image](https://github.com/slowy07/your_question/assets/88574877/7d96ebb6-2fa1-4c6b-a863-06aab343ff28)

**Comment by slowy07** [comment]
https://youtu.be/-rAdTt6OAoM?si=W4xWXk3k8KSyZ_BQ
