### ISSUE TITLE
Ask: AI vs Quantum Computing

### ISSUE THREAD

**Issue by rulanugrh** [slowy07/your_question#9]
![image](https://github.com/slowy07/your_question/assets/88574877/5dbd8c2b-198e-4668-b536-361a0b5ade6b)

## Question
Haii bang arfy, sekarang sedang maraknya AI terutama akhir akhir ini yang lagi ramai entah itu Devin AI, dsb. Namun di negara lain malah maraknya tentang Quantum Computing. Pertanyaanya apakah Quantum Computing ini akan bersaing dengan AI itu sendiri atau malah lebih parah lagi kontribusinya untuk di bidang IT. Entah berapa tahun quantum computing bakal ramai di semua negara, yang saya pikirkan apa dampak yang bakal terjadi 🤔 . Apaa di waktu itu system full diambil alih oleh quantum computing ? Lalu kapan itu terjadi ? asumsi ku mengatakan kayanya ini bakal terjadi dalam 5-10 tahun kedepan

**Comment by slowy07** [comment]
https://youtu.be/fjEKY6H7g9w?si=l9J32Yt0LTCFqhyb
